apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nu5h9d8xw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nu5h9d8xw-dotnet-basic-gitops